0 /musicscale/Zita_Light/Dry/Wet_Mix
-6 /musicscale/Zita_Light/Level
3 /musicscale/Common_Parameters/Pitch
0 /musicscale/Common_Parameters/Octave
0 /musicscale/Common_Parameters/Fine_Tune
2 /musicscale/Common_Parameters/Period
-203 /musicscale/Common_Parameters/12_Note_Scale/Sa/Cent
-91 /musicscale/Common_Parameters/12_Note_Scale/Sa/0.01_Cent
-111 /musicscale/Common_Parameters/12_Note_Scale/re/Cent
-73 /musicscale/Common_Parameters/12_Note_Scale/re/0.01_Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Re/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Re/0.01_Cent
-203 /musicscale/Common_Parameters/12_Note_Scale/ga/Cent
-91 /musicscale/Common_Parameters/12_Note_Scale/ga/0.01_Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Ga/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Ga/0.01_Cent
-203 /musicscale/Common_Parameters/12_Note_Scale/ma/Cent
-91 /musicscale/Common_Parameters/12_Note_Scale/ma/0.01_Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Ma/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Ma/0.01_Cent
-203 /musicscale/Common_Parameters/12_Note_Scale/Pa/Cent
-91 /musicscale/Common_Parameters/12_Note_Scale/Pa/0.01_Cent
-111 /musicscale/Common_Parameters/12_Note_Scale/dha/Cent
-73 /musicscale/Common_Parameters/12_Note_Scale/dha/0.01_Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Dha/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Dha/0.01_Cent
-203 /musicscale/Common_Parameters/12_Note_Scale/ni/Cent
-91 /musicscale/Common_Parameters/12_Note_Scale/ni/0.01_Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Ni/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Ni/0.01_Cent
-203 /musicscale/Common_Parameters/12_Note_Scale/SA/Cent
-91 /musicscale/Common_Parameters/12_Note_Scale/SA/0.01_Cent