import "@fontsource/noto-sans/400.css"
import "@fontsource/noto-sans/400-italic.css"
import "@fontsource/noto-sans/700.css"
import "@fontsource/noto-sans/700-italic.css"
import "@fontsource/roboto-mono/400.css"