0 /musicscale/Common_Parameters/12_Note_Scale/Sa/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Sa/0.01_Cent
-22 /musicscale/Common_Parameters/12_Note_Scale/Re/Cent
49 /musicscale/Common_Parameters/12_Note_Scale/Re/0.01_Cent
0 /musicscale/Common_Parameters/12_Note_Scale/ga/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/ga/0.01_Cent
0 /musicscale/Common_Parameters/12_Note_Scale/ma/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/ma/0.01_Cent
-22 /musicscale/Common_Parameters/12_Note_Scale/Pa/Cent
49 /musicscale/Common_Parameters/12_Note_Scale/Pa/0.01_Cent
0 /musicscale/Common_Parameters/12_Note_Scale/dha/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/dha/0.01_Cent
0 /musicscale/Common_Parameters/12_Note_Scale/ni/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/ni/0.01_Cent