0 /musicscale/Common_Parameters/12_Note_Scale/Sa/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Sa/0.01_Cent
12 /musicscale/Common_Parameters/12_Note_Scale/re/Cent
-27 /musicscale/Common_Parameters/12_Note_Scale/re/0.01_Cent
10 /musicscale/Common_Parameters/12_Note_Scale/Ga/Cent
-22 /musicscale/Common_Parameters/12_Note_Scale/Ga/0.01_Cent
0 /musicscale/Common_Parameters/12_Note_Scale/ma/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/ma/0.01_Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Pa/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Pa/0.01_Cent
12 /musicscale/Common_Parameters/12_Note_Scale/dha/Cent
-27 /musicscale/Common_Parameters/12_Note_Scale/dha/0.01_Cent
-12 /musicscale/Common_Parameters/12_Note_Scale/Ni/Cent
27 /musicscale/Common_Parameters/12_Note_Scale/Ni/0.01_Cent