0 /musicscale/Common_Parameters/12_Note_Scale/Sa/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Sa/0.01_Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Re/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Re/0.01_Cent
-11 /musicscale/Common_Parameters/12_Note_Scale/Ga/Cent
25 /musicscale/Common_Parameters/12_Note_Scale/Ga/0.01_Cent
-22 /musicscale/Common_Parameters/12_Note_Scale/Ma/Cent
49 /musicscale/Common_Parameters/12_Note_Scale/Ma/0.01_Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Pa/Cent
0 /musicscale/Common_Parameters/12_Note_Scale/Pa/0.01_Cent
-11 /musicscale/Common_Parameters/12_Note_Scale/Dha/Cent
25 /musicscale/Common_Parameters/12_Note_Scale/Dha/0.01_Cent
-22 /musicscale/Common_Parameters/12_Note_Scale/Ni/Cent
49 /musicscale/Common_Parameters/12_Note_Scale/Ni/0.01_Cent